// client/src/redux/actionTypes/achievementActionTypes.js

// === ADMIN ACTIONS ===

// Get all achievements for admin management
export const ADMIN_GET_ACHIEVEMENTS_REQUEST = "ADMIN_GET_ACHIEVEMENTS_REQUEST";
export const ADMIN_GET_ACHIEVEMENTS_SUCCESS = "ADMIN_GET_ACHIEVEMENTS_SUCCESS";
export const ADMIN_GET_ACHIEVEMENTS_FAIL = "ADMIN_GET_ACHIEVEMENTS_FAIL";

// Create a new achievement
export const ADMIN_CREATE_ACHIEVEMENT_REQUEST = "ADMIN_CREATE_ACHIEVEMENT_REQUEST";
export const ADMIN_CREATE_ACHIEVEMENT_SUCCESS = "ADMIN_CREATE_ACHIEVEMENT_SUCCESS";
export const ADMIN_CREATE_ACHIEVEMENT_FAIL = "ADMIN_CREATE_ACHIEVEMENT_FAIL";
export const ADMIN_CREATE_ACHIEVEMENT_RESET = "ADMIN_CREATE_ACHIEVEMENT_RESET";

// Update an achievement
export const ADMIN_UPDATE_ACHIEVEMENT_REQUEST = "ADMIN_UPDATE_ACHIEVEMENT_REQUEST";
export const ADMIN_UPDATE_ACHIEVEMENT_SUCCESS = "ADMIN_UPDATE_ACHIEVEMENT_SUCCESS";
export const ADMIN_UPDATE_ACHIEVEMENT_FAIL = "ADMIN_UPDATE_ACHIEVEMENT_FAIL";
export const ADMIN_UPDATE_ACHIEVEMENT_RESET = "ADMIN_UPDATE_ACHIEVEMENT_RESET";


// Delete an achievement
export const ADMIN_DELETE_ACHIEVEMENT_REQUEST = "ADMIN_DELETE_ACHIEVEMENT_REQUEST";
export const ADMIN_DELETE_ACHIEVEMENT_SUCCESS = "ADMIN_DELETE_ACHIEVEMENT_SUCCESS";
export const ADMIN_DELETE_ACHIEVEMENT_FAIL = "ADMIN_DELETE_ACHIEVEMENT_FAIL";


// === PUBLIC/USER ACTIONS ===

// Get all available (non-secret) achievements for users to view
export const GET_AVAILABLE_ACHIEVEMENTS_REQUEST = "GET_AVAILABLE_ACHIEVEMENTS_REQUEST";
export const GET_AVAILABLE_ACHIEVEMENTS_SUCCESS = "GET_AVAILABLE_ACHIEVEMENTS_SUCCESS";
export const GET_AVAILABLE_ACHIEVEMENTS_FAIL = "GET_AVAILABLE_ACHIEVEMENTS_FAIL";

// Action to update user's achievements in the userReducer
export const UPDATE_USER_ACHIEVEMENTS_IN_STORE = "UPDATE_USER_ACHIEVEMENTS_IN_STORE";


// === UTILITY ===
export const CLEAR_ACHIEVEMENT_ERRORS = "CLEAR_ACHIEVEMENT_ERRORS";