// src/redux/actionTypes/adminUserActionType.js
export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL';
export const UPDATE_USER_STATUS_REQUEST = 'UPDATE_USER_STATUS_REQUEST';
export const UPDATE_USER_STATUS_SUCCESS = 'UPDATE_USER_STATUS_SUCCESS';
export const UPDATE_USER_STATUS_FAIL = 'UPDATE_USER_STATUS_FAIL';
export const ADMIN_UPDATE_USER_DATA_REQUEST = 'ADMIN_UPDATE_USER_DATA_REQUEST';
export const ADMIN_UPDATE_USER_DATA_SUCCESS = 'ADMIN_UPDATE_USER_DATA_SUCCESS';
export const ADMIN_UPDATE_USER_DATA_FAIL = 'ADMIN_UPDATE_USER_DATA_FAIL';
export const CLEAR_ADMIN_USER_ERRORS = 'CLEAR_ADMIN_USER_ERRORS';