export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";

// أحداث الوقت الحقيقي (Socket)
export const ADD_MESSAGE_REALTIME = "ADD_MESSAGE_REALTIME";
export const MESSAGE_DELETED_REALTIME = "MESSAGE_DELETED_REALTIME";
export const MESSAGE_PINNED_REALTIME = "MESSAGE_PINNED_REALTIME";
export const CHAT_CLEARED_REALTIME = "CHAT_CLEARED_REALTIME";