// src/redux/actionTypes/faqActionTypes.js
export const GET_FAQS_REQUEST = 'GET_FAQS_REQUEST';
export const GET_FAQS_SUCCESS = 'GET_FAQS_SUCCESS';
export const GET_FAQS_FAIL = 'GET_FAQS_FAIL';

// Admin actions
export const ADMIN_GET_ALL_FAQS_REQUEST = 'ADMIN_GET_ALL_FAQS_REQUEST';
export const ADMIN_GET_ALL_FAQS_SUCCESS = 'ADMIN_GET_ALL_FAQS_SUCCESS';
export const ADMIN_GET_ALL_FAQS_FAIL = 'ADMIN_GET_ALL_FAQS_FAIL';

export const ADMIN_CREATE_FAQ_REQUEST = 'ADMIN_CREATE_FAQ_REQUEST';
export const ADMIN_CREATE_FAQ_SUCCESS = 'ADMIN_CREATE_FAQ_SUCCESS';
export const ADMIN_CREATE_FAQ_FAIL = 'ADMIN_CREATE_FAQ_FAIL';
export const ADMIN_CREATE_FAQ_RESET = 'ADMIN_CREATE_FAQ_RESET';

export const ADMIN_UPDATE_FAQ_REQUEST = 'ADMIN_UPDATE_FAQ_REQUEST';
export const ADMIN_UPDATE_FAQ_SUCCESS = 'ADMIN_UPDATE_FAQ_SUCCESS';
export const ADMIN_UPDATE_FAQ_FAIL = 'ADMIN_UPDATE_FAQ_FAIL';
export const ADMIN_UPDATE_FAQ_RESET = 'ADMIN_UPDATE_FAQ_RESET';

export const ADMIN_DELETE_FAQ_REQUEST = 'ADMIN_DELETE_FAQ_REQUEST';
export const ADMIN_DELETE_FAQ_SUCCESS = 'ADMIN_DELETE_FAQ_SUCCESS';
export const ADMIN_DELETE_FAQ_FAIL = 'ADMIN_DELETE_FAQ_FAIL';

export const CLEAR_FAQ_ERRORS = 'CLEAR_FAQ_ERRORS';