// src/redux/actionTypes/leagueActionTypes.js

// --- LEAGUES ---
export const GET_LEAGUES_REQUEST = 'GET_LEAGUES_REQUEST';
export const GET_LEAGUES_SUCCESS = 'GET_LEAGUES_SUCCESS';
export const GET_LEAGUES_FAIL = 'GET_LEAGUES_FAIL';

export const CREATE_LEAGUE_REQUEST = 'CREATE_LEAGUE_REQUEST';
export const CREATE_LEAGUE_SUCCESS = 'CREATE_LEAGUE_SUCCESS';
export const CREATE_LEAGUE_FAIL = 'CREATE_LEAGUE_FAIL';

export const UPDATE_LEAGUE_REQUEST = 'UPDATE_LEAGUE_REQUEST';
export const UPDATE_LEAGUE_SUCCESS = 'UPDATE_LEAGUE_SUCCESS';
export const UPDATE_LEAGUE_FAIL = 'UPDATE_LEAGUE_FAIL';

export const DELETE_LEAGUE_REQUEST = 'DELETE_LEAGUE_REQUEST';
export const DELETE_LEAGUE_SUCCESS = 'DELETE_LEAGUE_SUCCESS';
export const DELETE_LEAGUE_FAIL = 'DELETE_LEAGUE_FAIL';

// --- TEAMS ---
export const GET_TEAMS_REQUEST = 'GET_TEAMS_REQUEST';
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';
export const GET_TEAMS_FAIL = 'GET_TEAMS_FAIL';

export const ADD_TEAM_REQUEST = 'ADD_TEAM_REQUEST';
export const ADD_TEAM_SUCCESS = 'ADD_TEAM_SUCCESS';
export const ADD_TEAM_FAIL = 'ADD_TEAM_FAIL';

export const UPDATE_TEAM_REQUEST = 'UPDATE_TEAM_REQUEST';
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS';
export const UPDATE_TEAM_FAIL = 'UPDATE_TEAM_FAIL';

export const DELETE_TEAM_REQUEST = 'DELETE_TEAM_REQUEST';
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS';
export const DELETE_TEAM_FAIL = 'DELETE_TEAM_FAIL';

export const CLEAR_LEAGUE_ERRORS = 'CLEAR_LEAGUE_ERRORS';