// src/redux/actionTypes/mediationActionTypes.js

// جلب طلبات الوساطة المعلقة (للأدمن)
export const ADMIN_GET_PENDING_ASSIGNMENTS_REQUEST = "ADMIN_GET_PENDING_ASSIGNMENTS_REQUEST";
export const ADMIN_GET_PENDING_ASSIGNMENTS_SUCCESS = "ADMIN_GET_PENDING_ASSIGNMENTS_SUCCESS";
export const ADMIN_GET_PENDING_ASSIGNMENTS_FAIL = "ADMIN_GET_PENDING_ASSIGNMENTS_FAIL";

// تعيين وسيط لطلب (للأدمن)
export const ADMIN_ASSIGN_MEDIATOR_REQUEST = "ADMIN_ASSIGN_MEDIATOR_REQUEST";
export const ADMIN_ASSIGN_MEDIATOR_SUCCESS = "ADMIN_ASSIGN_MEDIATOR_SUCCESS";
export const ADMIN_ASSIGN_MEDIATOR_FAIL = "ADMIN_ASSIGN_MEDIATOR_FAIL";
export const ADMIN_ASSIGN_MEDIATOR_RESET = "ADMIN_ASSIGN_MEDIATOR_RESET"; // لإعادة تعيين حالة النجاح/الفشل

// مسح أخطاء الوساطة (للأدمن)
export const ADMIN_CLEAR_MEDIATION_ERRORS = "ADMIN_CLEAR_MEDIATION_ERRORS";

// --- (أضف أنواعًا أخرى لاحقًا للوسيط والأطراف) ---
// مثل: MEDIATOR_GET_ASSIGNMENTS, MEDIATOR_ACCEPT_REQUEST, MEDIATOR_REJECT_REQUEST, etc.