// src/redux/actionTypes/mediationActionTypes.js

// جلب طلبات الوساطة المعلقة (للأدمن)
export const ADMIN_GET_PENDING_ASSIGNMENTS_REQUEST = "ADMIN_GET_PENDING_ASSIGNMENTS_REQUEST";
export const ADMIN_GET_PENDING_ASSIGNMENTS_SUCCESS = "ADMIN_GET_PENDING_ASSIGNMENTS_SUCCESS";
export const ADMIN_GET_PENDING_ASSIGNMENTS_FAIL = "ADMIN_GET_PENDING_ASSIGNMENTS_FAIL";

// تعيين وسيط لطلب (للأدمن)
export const ADMIN_ASSIGN_MEDIATOR_REQUEST = "ADMIN_ASSIGN_MEDIATOR_REQUEST";
export const ADMIN_ASSIGN_MEDIATOR_SUCCESS = "ADMIN_ASSIGN_MEDIATOR_SUCCESS";
export const ADMIN_ASSIGN_MEDIATOR_FAIL = "ADMIN_ASSIGN_MEDIATOR_FAIL";
export const ADMIN_ASSIGN_MEDIATOR_RESET = "ADMIN_ASSIGN_MEDIATOR_RESET"; // لإعادة تعيين حالة النجاح/الفشل

// مسح أخطاء الوساطة (للأدمن)
export const ADMIN_CLEAR_MEDIATION_ERRORS = "ADMIN_CLEAR_MEDIATION_ERRORS";

export const ASSIGN_MEDIATOR_REQUEST = 'ASSIGN_MEDIATOR_REQUEST';
export const ASSIGN_MEDIATOR_SUCCESS = 'ASSIGN_MEDIATOR_SUCCESS';
export const ASSIGN_MEDIATOR_FAIL = 'ASSIGN_MEDIATOR_FAIL';

// --- (أضف أنواعًا أخرى لاحقًا للوسيط والأطراف) ---
export const GET_MEDIATOR_ASSIGNMENTS_REQUEST = 'GET_MEDIATOR_ASSIGNMENTS_REQUEST';
export const GET_MEDIATOR_ASSIGNMENTS_SUCCESS = 'GET_MEDIATOR_ASSIGNMENTS_SUCCESS';
export const GET_MEDIATOR_ASSIGNMENTS_FAIL = 'GET_MEDIATOR_ASSIGNMENTS_FAIL';

// Action types لـ accept/reject ستأتي لاحقًا
export const MEDIATOR_ACCEPT_ASSIGNMENT_REQUEST = 'MEDIATOR_ACCEPT_ASSIGNMENT_REQUEST';
export const MEDIATOR_ACCEPT_ASSIGNMENT_SUCCESS = 'MEDIATOR_ACCEPT_ASSIGNMENT_SUCCESS';
export const MEDIATOR_ACCEPT_ASSIGNMENT_FAIL = 'MEDIATOR_ACCEPT_ASSIGNMENT_FAIL';

export const MEDIATOR_REJECT_ASSIGNMENT_REQUEST = 'MEDIATOR_REJECT_ASSIGNMENT_REQUEST';
export const MEDIATOR_REJECT_ASSIGNMENT_SUCCESS = 'MEDIATOR_REJECT_ASSIGNMENT_SUCCESS';
export const MEDIATOR_REJECT_ASSIGNMENT_FAIL = 'MEDIATOR_REJECT_ASSIGNMENT_FAIL';

export const GET_MEDIATOR_ACCEPTED_AWAITING_PARTIES_REQUEST = 'GET_MEDIATOR_ACCEPTED_AWAITING_PARTIES_REQUEST';
export const GET_MEDIATOR_ACCEPTED_AWAITING_PARTIES_SUCCESS = 'GET_MEDIATOR_ACCEPTED_AWAITING_PARTIES_SUCCESS';
export const GET_MEDIATOR_ACCEPTED_AWAITING_PARTIES_FAIL = 'GET_MEDIATOR_ACCEPTED_AWAITING_PARTIES_FAIL';

export const GET_BUYER_MEDIATION_REQUESTS_REQUEST = 'GET_BUYER_MEDIATION_REQUESTS_REQUEST';
export const GET_BUYER_MEDIATION_REQUESTS_SUCCESS = 'GET_BUYER_MEDIATION_REQUESTS_SUCCESS';
export const GET_BUYER_MEDIATION_REQUESTS_FAIL = 'GET_BUYER_MEDIATION_REQUESTS_FAIL';

// --- Seller Confirm Readiness ---
export const SELLER_CONFIRM_READINESS_REQUEST = 'SELLER_CONFIRM_READINESS_REQUEST';
export const SELLER_CONFIRM_READINESS_SUCCESS = 'SELLER_CONFIRM_READINESS_SUCCESS';
export const SELLER_CONFIRM_READINESS_FAIL = 'SELLER_CONFIRM_READINESS_FAIL';

// --- Buyer Confirm Readiness & Escrow ---
export const BUYER_CONFIRM_READINESS_ESCROW_REQUEST = 'BUYER_CONFIRM_READINESS_ESCROW_REQUEST';
export const BUYER_CONFIRM_READINESS_ESCROW_SUCCESS = 'BUYER_CONFIRM_READINESS_ESCROW_SUCCESS';
export const BUYER_CONFIRM_READINESS_ESCROW_FAIL = 'BUYER_CONFIRM_READINESS_ESCROW_FAIL';