// src/redux/actionTypes/mediationActionTypes.js

// --- Admin: General Mediation Management ---
export const ADMIN_GET_PENDING_ASSIGNMENTS_REQUEST = 'ADMIN_GET_PENDING_ASSIGNMENTS_REQUEST';
export const ADMIN_GET_PENDING_ASSIGNMENTS_SUCCESS = 'ADMIN_GET_PENDING_ASSIGNMENTS_SUCCESS';
export const ADMIN_GET_PENDING_ASSIGNMENTS_FAIL = 'ADMIN_GET_PENDING_ASSIGNMENTS_FAIL';

export const ADMIN_ASSIGN_MEDIATOR_REQUEST = 'ADMIN_ASSIGN_MEDIATOR_REQUEST';
export const ADMIN_ASSIGN_MEDIATOR_SUCCESS = 'ADMIN_ASSIGN_MEDIATOR_SUCCESS';
export const ADMIN_ASSIGN_MEDIATOR_FAIL = 'ADMIN_ASSIGN_MEDIATOR_FAIL';
export const ADMIN_ASSIGN_MEDIATOR_RESET = 'ADMIN_ASSIGN_MEDIATOR_RESET';

export const ADMIN_GET_DISPUTED_MEDIATIONS_REQUEST = 'ADMIN_GET_DISPUTED_MEDIATIONS_REQUEST';
export const ADMIN_GET_DISPUTED_MEDIATIONS_SUCCESS = 'ADMIN_GET_DISPUTED_MEDIATIONS_SUCCESS';
export const ADMIN_GET_DISPUTED_MEDIATIONS_FAIL = 'ADMIN_GET_DISPUTED_MEDIATIONS_FAIL';

export const ADMIN_RESOLVE_DISPUTE_REQUEST = 'ADMIN_RESOLVE_DISPUTE_REQUEST';
export const ADMIN_RESOLVE_DISPUTE_SUCCESS = 'ADMIN_RESOLVE_DISPUTE_SUCCESS';
export const ADMIN_RESOLVE_DISPUTE_FAIL = 'ADMIN_RESOLVE_DISPUTE_FAIL';

export const ADMIN_CLEAR_MEDIATION_ERRORS = 'ADMIN_CLEAR_MEDIATION_ERRORS';


// --- Seller Actions ---
export const ASSIGN_MEDIATOR_REQUEST = 'ASSIGN_MEDIATOR_REQUEST'; // Seller assigns selected
export const ASSIGN_MEDIATOR_SUCCESS = 'ASSIGN_MEDIATOR_SUCCESS';
export const ASSIGN_MEDIATOR_FAIL = 'ASSIGN_MEDIATOR_FAIL';

export const SELLER_CONFIRM_READINESS_REQUEST = 'SELLER_CONFIRM_READINESS_REQUEST';
export const SELLER_CONFIRM_READINESS_SUCCESS = 'SELLER_CONFIRM_READINESS_SUCCESS';
export const SELLER_CONFIRM_READINESS_FAIL = 'SELLER_CONFIRM_READINESS_FAIL';

// --- Buyer Actions ---
export const GET_BUYER_MEDIATION_REQUESTS_REQUEST = 'GET_BUYER_MEDIATION_REQUESTS_REQUEST';
export const GET_BUYER_MEDIATION_REQUESTS_SUCCESS = 'GET_BUYER_MEDIATION_REQUESTS_SUCCESS';
export const GET_BUYER_MEDIATION_REQUESTS_FAIL = 'GET_BUYER_MEDIATION_REQUESTS_FAIL';

export const BUYER_CONFIRM_READINESS_ESCROW_REQUEST = 'BUYER_CONFIRM_READINESS_ESCROW_REQUEST';
export const BUYER_CONFIRM_READINESS_ESCROW_SUCCESS = 'BUYER_CONFIRM_READINESS_ESCROW_SUCCESS';
export const BUYER_CONFIRM_READINESS_ESCROW_FAIL = 'BUYER_CONFIRM_READINESS_ESCROW_FAIL';

export const BUYER_REJECT_MEDIATION_REQUEST = 'BUYER_REJECT_MEDIATION_REQUEST';
export const BUYER_REJECT_MEDIATION_SUCCESS = 'BUYER_REJECT_MEDIATION_SUCCESS';
export const BUYER_REJECT_MEDIATION_FAIL = 'BUYER_REJECT_MEDIATION_FAIL';

export const BUYER_CONFIRM_RECEIPT_REQUEST = 'BUYER_CONFIRM_RECEIPT_REQUEST';
export const BUYER_CONFIRM_RECEIPT_SUCCESS = 'BUYER_CONFIRM_RECEIPT_SUCCESS';
export const BUYER_CONFIRM_RECEIPT_FAIL = 'BUYER_CONFIRM_RECEIPT_FAIL';

// --- Mediator Actions ---
export const GET_MEDIATOR_ASSIGNMENTS_REQUEST = 'GET_MEDIATOR_ASSIGNMENTS_REQUEST'; // Pending decision
export const GET_MEDIATOR_ASSIGNMENTS_SUCCESS = 'GET_MEDIATOR_ASSIGNMENTS_SUCCESS';
export const GET_MEDIATOR_ASSIGNMENTS_FAIL = 'GET_MEDIATOR_ASSIGNMENTS_FAIL';

export const MEDIATOR_ACCEPT_ASSIGNMENT_REQUEST = 'MEDIATOR_ACCEPT_ASSIGNMENT_REQUEST';
export const MEDIATOR_ACCEPT_ASSIGNMENT_SUCCESS = 'MEDIATOR_ACCEPT_ASSIGNMENT_SUCCESS';
export const MEDIATOR_ACCEPT_ASSIGNMENT_FAIL = 'MEDIATOR_ACCEPT_ASSIGNMENT_FAIL';

export const MEDIATOR_REJECT_ASSIGNMENT_REQUEST = 'MEDIATOR_REJECT_ASSIGNMENT_REQUEST';
export const MEDIATOR_REJECT_ASSIGNMENT_SUCCESS = 'MEDIATOR_REJECT_ASSIGNMENT_SUCCESS';
export const MEDIATOR_REJECT_ASSIGNMENT_FAIL = 'MEDIATOR_REJECT_ASSIGNMENT_FAIL';

export const GET_MEDIATOR_ACCEPTED_AWAITING_PARTIES_REQUEST = 'GET_MEDIATOR_ACCEPTED_AWAITING_PARTIES_REQUEST';
export const GET_MEDIATOR_ACCEPTED_AWAITING_PARTIES_SUCCESS = 'GET_MEDIATOR_ACCEPTED_AWAITING_PARTIES_SUCCESS';
export const GET_MEDIATOR_ACCEPTED_AWAITING_PARTIES_FAIL = 'GET_MEDIATOR_ACCEPTED_AWAITING_PARTIES_FAIL';

export const GET_MEDIATOR_DISPUTED_CASES_REQUEST = 'GET_MEDIATOR_DISPUTED_CASES_REQUEST';
export const GET_MEDIATOR_DISPUTED_CASES_SUCCESS = 'GET_MEDIATOR_DISPUTED_CASES_SUCCESS';
export const GET_MEDIATOR_DISPUTED_CASES_FAIL = 'GET_MEDIATOR_DISPUTED_CASES_FAIL';

// --- General Mediation Details & Chat List ---
export const GET_MEDIATION_DETAILS_BY_ID_REQUEST = 'GET_MEDIATION_DETAILS_BY_ID_REQUEST';
export const GET_MEDIATION_DETAILS_BY_ID_SUCCESS = 'GET_MEDIATION_DETAILS_BY_ID_SUCCESS';
export const GET_MEDIATION_DETAILS_BY_ID_FAIL = 'GET_MEDIATION_DETAILS_BY_ID_FAIL';
export const CLEAR_ACTIVE_MEDIATION_DETAILS = 'CLEAR_ACTIVE_MEDIATION_DETAILS';

export const GET_MY_MEDIATION_SUMMARIES_REQUEST = 'GET_MY_MEDIATION_SUMMARIES_REQUEST';
export const GET_MY_MEDIATION_SUMMARIES_SUCCESS = 'GET_MY_MEDIATION_SUMMARIES_SUCCESS';
export const GET_MY_MEDIATION_SUMMARIES_FAIL = 'GET_MY_MEDIATION_SUMMARIES_FAIL';

export const OPEN_DISPUTE_REQUEST = 'OPEN_DISPUTE_REQUEST';
export const OPEN_DISPUTE_SUCCESS = 'OPEN_DISPUTE_SUCCESS';
export const OPEN_DISPUTE_FAIL = 'OPEN_DISPUTE_FAIL';

// --- Socket & UI Updates for Chat ---
export const UPDATE_MEDIATION_DETAILS_FROM_SOCKET = 'UPDATE_MEDIATION_DETAILS_FROM_SOCKET';
export const MARK_MEDIATION_AS_READ_IN_LIST = 'MARK_MEDIATION_AS_READ_IN_LIST'; // For chat list UI
export const UPDATE_UNREAD_COUNT_FROM_SOCKET = 'UPDATE_UNREAD_COUNT_FROM_SOCKET'; // For chat list UI

// --- Admin Sub-Chat Actions ---
export const ADMIN_CREATE_SUBCHAT_REQUEST = 'ADMIN_CREATE_SUBCHAT_REQUEST';
export const ADMIN_CREATE_SUBCHAT_SUCCESS = 'ADMIN_CREATE_SUBCHAT_SUCCESS';
export const ADMIN_CREATE_SUBCHAT_FAIL = 'ADMIN_CREATE_SUBCHAT_FAIL';
export const ADMIN_CREATE_SUBCHAT_RESET = 'ADMIN_CREATE_SUBCHAT_RESET';

export const ADMIN_GET_ALL_SUBCHATS_REQUEST = 'ADMIN_GET_ALL_SUBCHATS_REQUEST';
export const ADMIN_GET_ALL_SUBCHATS_SUCCESS = 'ADMIN_GET_ALL_SUBCHATS_SUCCESS';
export const ADMIN_GET_ALL_SUBCHATS_FAIL = 'ADMIN_GET_ALL_SUBCHATS_FAIL';

export const ADMIN_GET_SUBCHAT_MESSAGES_REQUEST = 'ADMIN_GET_SUBCHAT_MESSAGES_REQUEST';
export const ADMIN_GET_SUBCHAT_MESSAGES_SUCCESS = 'ADMIN_GET_SUBCHAT_MESSAGES_SUCCESS';
export const ADMIN_GET_SUBCHAT_MESSAGES_FAIL = 'ADMIN_GET_SUBCHAT_MESSAGES_FAIL';
export const CLEAR_ACTIVE_SUBCHAT_MESSAGES = 'CLEAR_ACTIVE_SUBCHAT_MESSAGES';

export const ADMIN_SEND_SUBCHAT_MESSAGE_REQUEST = 'ADMIN_SEND_SUBCHAT_MESSAGE_REQUEST';
export const ADMIN_SEND_SUBCHAT_MESSAGE_SUCCESS = 'ADMIN_SEND_SUBCHAT_MESSAGE_SUCCESS';
export const ADMIN_SEND_SUBCHAT_MESSAGE_FAIL = 'ADMIN_SEND_SUBCHAT_MESSAGE_FAIL';

export const ADMIN_SUBCHAT_CREATED_SOCKET = 'ADMIN_SUBCHAT_CREATED_SOCKET';
export const NEW_ADMIN_SUBCHAT_MESSAGE_SOCKET = 'NEW_ADMIN_SUBCHAT_MESSAGE_SOCKET';
export const ADMIN_SUBCHAT_MESSAGES_STATUS_UPDATED_SOCKET = 'ADMIN_SUBCHAT_MESSAGES_STATUS_UPDATED_SOCKET';

export const SET_ACTIVE_SUBCHAT_ID = 'SET_ACTIVE_SUBCHAT_ID';

export const UPDATE_SINGLE_MEDIATION_REQUEST_IN_STORE = 'UPDATE_SINGLE_MEDIATION_REQUEST_IN_STORE';

export const ADD_SUB_CHAT_TO_MEDIATION = 'ADD_SUB_CHAT_TO_MEDIATION';
export const UPDATE_SUBCHAT_MESSAGES_READ_STATUS = 'UPDATE_SUBCHAT_MESSAGES_READ_STATUS';

export const ADD_PENDING_ASSIGNMENT_FROM_SOCKET = 'ADD_PENDING_ASSIGNMENT_FROM_SOCKET';