// client/src/redux/actionTypes/newsActionTypes.js

export const GET_NEWS_REQUEST = "GET_NEWS_REQUEST";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_FAIL = "GET_NEWS_FAIL";

export const LIKE_NEWS_REQUEST = "LIKE_NEWS_REQUEST";
export const LIKE_NEWS_SUCCESS = "LIKE_NEWS_SUCCESS";
export const LIKE_NEWS_FAIL = "LIKE_NEWS_FAIL";

export const DISLIKE_NEWS_REQUEST = "DISLIKE_NEWS_REQUEST";
export const DISLIKE_NEWS_SUCCESS = "DISLIKE_NEWS_SUCCESS";
export const DISLIKE_NEWS_FAIL = "DISLIKE_NEWS_FAIL";

export const MARK_NEWS_READ_REQUEST = "MARK_NEWS_READ_REQUEST";
export const MARK_NEWS_READ_SUCCESS = "MARK_NEWS_READ_SUCCESS";
export const MARK_NEWS_READ_FAIL = "MARK_NEWS_READ_FAIL";

// Actions for Admin
export const ADMIN_CREATE_NEWS_REQUEST = "ADMIN_CREATE_NEWS_REQUEST";
export const ADMIN_CREATE_NEWS_SUCCESS = "ADMIN_CREATE_NEWS_SUCCESS";
export const ADMIN_CREATE_NEWS_FAIL = "ADMIN_CREATE_NEWS_FAIL";
export const ADMIN_CREATE_NEWS_RESET = "ADMIN_CREATE_NEWS_RESET";

export const ADMIN_UPDATE_NEWS_REQUEST = "ADMIN_UPDATE_NEWS_REQUEST";
export const ADMIN_UPDATE_NEWS_SUCCESS = "ADMIN_UPDATE_NEWS_SUCCESS";
export const ADMIN_UPDATE_NEWS_FAIL = "ADMIN_UPDATE_NEWS_FAIL";

export const ADMIN_DELETE_NEWS_REQUEST = "ADMIN_DELETE_NEWS_REQUEST";
export const ADMIN_DELETE_NEWS_SUCCESS = "ADMIN_DELETE_NEWS_SUCCESS";
export const ADMIN_DELETE_NEWS_FAIL = "ADMIN_DELETE_NEWS_FAIL";

export const CLEAR_NEWS_ERRORS = "CLEAR_NEWS_ERRORS";