// src/redux/actionTypes/notificationActionType.js
export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAIL = 'GET_NOTIFICATIONS_FAIL';
export const MARK_READ_REQUEST = 'MARK_READ_REQUEST';
export const MARK_READ_SUCCESS = 'MARK_READ_SUCCESS';
export const MARK_READ_FAIL = 'MARK_READ_FAIL';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS'; // <-- مضاف