// src/redux/actionTypes/paymentMethodActionTypes.js

// جلب الطرق النشطة (للمستخدمين)
export const GET_ACTIVE_METHODS_REQUEST = 'GET_ACTIVE_METHODS_REQUEST';
export const GET_ACTIVE_METHODS_SUCCESS = 'GET_ACTIVE_METHODS_SUCCESS';
export const GET_ACTIVE_METHODS_FAIL =    'GET_ACTIVE_METHODS_FAIL';

// إدارة الطرق (للأدمن)
export const ADMIN_GET_ALL_METHODS_REQUEST = 'ADMIN_GET_ALL_METHODS_REQUEST';
export const ADMIN_GET_ALL_METHODS_SUCCESS = 'ADMIN_GET_ALL_METHODS_SUCCESS';
export const ADMIN_GET_ALL_METHODS_FAIL =    'ADMIN_GET_ALL_METHODS_FAIL';

export const ADMIN_ADD_METHOD_REQUEST = 'ADMIN_ADD_METHOD_REQUEST';
export const ADMIN_ADD_METHOD_SUCCESS = 'ADMIN_ADD_METHOD_SUCCESS';
export const ADMIN_ADD_METHOD_FAIL =    'ADMIN_ADD_METHOD_FAIL';

export const ADMIN_UPDATE_METHOD_REQUEST = 'ADMIN_UPDATE_METHOD_REQUEST';
export const ADMIN_UPDATE_METHOD_SUCCESS = 'ADMIN_UPDATE_METHOD_SUCCESS';
export const ADMIN_UPDATE_METHOD_FAIL =    'ADMIN_UPDATE_METHOD_FAIL';

export const ADMIN_DELETE_METHOD_REQUEST = 'ADMIN_DELETE_METHOD_REQUEST';
export const ADMIN_DELETE_METHOD_SUCCESS = 'ADMIN_DELETE_METHOD_SUCCESS';
export const ADMIN_DELETE_METHOD_FAIL =    'ADMIN_DELETE_METHOD_FAIL';

// مسح الأخطاء
export const CLEAR_PAYMENT_METHOD_ERROR = 'CLEAR_PAYMENT_METHOD_ERROR';