export const GET_QUESTS_REQUEST = "GET_QUESTS_REQUEST";
export const GET_QUESTS_SUCCESS = "GET_QUESTS_SUCCESS";
export const GET_QUESTS_FAIL = "GET_QUESTS_FAIL";

export const CHECK_IN_REQUEST = "CHECK_IN_REQUEST";
export const CHECK_IN_SUCCESS = "CHECK_IN_SUCCESS";
export const CHECK_IN_FAIL = "CHECK_IN_FAIL";

export const CLAIM_REWARD_REQUEST = "CLAIM_REWARD_REQUEST";
export const CLAIM_REWARD_SUCCESS = "CLAIM_REWARD_SUCCESS";
export const CLAIM_REWARD_FAIL = "CLAIM_REWARD_FAIL";

export const SPIN_WHEEL_REQUEST = "SPIN_WHEEL_REQUEST";
export const SPIN_WHEEL_SUCCESS = "SPIN_WHEEL_SUCCESS";
export const SPIN_WHEEL_FAIL = "SPIN_WHEEL_FAIL";

export const SET_CHECK_IN_CONFIG = "SET_CHECK_IN_CONFIG";
export const SET_WHEEL_CONFIG = "SET_WHEEL_CONFIG";