export const SUBMIT_RATING_REQUEST = 'SUBMIT_RATING_REQUEST';
export const SUBMIT_RATING_SUCCESS = 'SUBMIT_RATING_SUCCESS';
export const SUBMIT_RATING_FAIL = 'SUBMIT_RATING_FAIL';
export const SUBMIT_RATING_RESET = 'SUBMIT_RATING_RESET'; // لإعادة تعيين الحالة بعد النجاح

export const GET_RATINGS_FOR_MEDIATION_REQUEST = 'GET_RATINGS_FOR_MEDIATION_REQUEST';
export const GET_RATINGS_FOR_MEDIATION_SUCCESS = 'GET_RATINGS_FOR_MEDIATION_SUCCESS';
export const GET_RATINGS_FOR_MEDIATION_FAIL = 'GET_RATINGS_FOR_MEDIATION_FAIL';