export const GET_REFERRAL_STATS_REQUEST = "GET_REFERRAL_STATS_REQUEST";
export const GET_REFERRAL_STATS_SUCCESS = "GET_REFERRAL_STATS_SUCCESS";
export const GET_REFERRAL_STATS_FAIL = "GET_REFERRAL_STATS_FAIL";

export const BIND_REFERRAL_REQUEST = "BIND_REFERRAL_REQUEST";
export const BIND_REFERRAL_SUCCESS = "BIND_REFERRAL_SUCCESS";
export const BIND_REFERRAL_FAIL = "BIND_REFERRAL_FAIL";

export const TRANSFER_REFERRAL_BALANCE_REQUEST = "TRANSFER_REFERRAL_BALANCE_REQUEST";
export const TRANSFER_REFERRAL_BALANCE_SUCCESS = "TRANSFER_REFERRAL_BALANCE_SUCCESS";
export const TRANSFER_REFERRAL_BALANCE_FAIL = "TRANSFER_REFERRAL_BALANCE_FAIL";