// src/redux/actionTypes/tournamentActionTypes.js

// --- GET TOURNAMENTS (List) ---
export const GET_TOURNAMENTS_REQUEST = 'GET_TOURNAMENTS_REQUEST';
export const GET_TOURNAMENTS_SUCCESS = 'GET_TOURNAMENTS_SUCCESS';
export const GET_TOURNAMENTS_FAIL = 'GET_TOURNAMENTS_FAIL';

// --- GET SINGLE TOURNAMENT DETAILS ---
export const GET_TOURNAMENT_DETAILS_REQUEST = 'GET_TOURNAMENT_DETAILS_REQUEST';
export const GET_TOURNAMENT_DETAILS_SUCCESS = 'GET_TOURNAMENT_DETAILS_SUCCESS';
export const GET_TOURNAMENT_DETAILS_FAIL = 'GET_TOURNAMENT_DETAILS_FAIL';

// --- CREATE TOURNAMENT (Admin) ---
export const CREATE_TOURNAMENT_REQUEST = 'CREATE_TOURNAMENT_REQUEST';
export const CREATE_TOURNAMENT_SUCCESS = 'CREATE_TOURNAMENT_SUCCESS';
export const CREATE_TOURNAMENT_FAIL = 'CREATE_TOURNAMENT_FAIL';

// --- JOIN TOURNAMENT ---
export const JOIN_TOURNAMENT_REQUEST = 'JOIN_TOURNAMENT_REQUEST';
export const JOIN_TOURNAMENT_SUCCESS = 'JOIN_TOURNAMENT_SUCCESS';
export const JOIN_TOURNAMENT_FAIL = 'JOIN_TOURNAMENT_FAIL';

// --- CHANGE TEAM ---
export const CHANGE_TEAM_REQUEST = 'CHANGE_TEAM_REQUEST';
export const CHANGE_TEAM_SUCCESS = 'CHANGE_TEAM_SUCCESS';
export const CHANGE_TEAM_FAIL = 'CHANGE_TEAM_FAIL';

// --- CHECK-IN ---
export const CHECKIN_TOURNAMENT_REQUEST = 'CHECKIN_TOURNAMENT_REQUEST';
export const CHECKIN_TOURNAMENT_SUCCESS = 'CHECKIN_TOURNAMENT_SUCCESS';
export const CHECKIN_TOURNAMENT_FAIL = 'CHECKIN_TOURNAMENT_FAIL';

// --- START TOURNAMENT (Admin) ---
export const START_TOURNAMENT_REQUEST = 'START_TOURNAMENT_REQUEST';
export const START_TOURNAMENT_SUCCESS = 'START_TOURNAMENT_SUCCESS';
export const START_TOURNAMENT_FAIL = 'START_TOURNAMENT_FAIL';

// --- GET MATCHES (Bracket) ---
export const GET_MATCHES_REQUEST = 'GET_MATCHES_REQUEST';
export const GET_MATCHES_SUCCESS = 'GET_MATCHES_SUCCESS';
export const GET_MATCHES_FAIL = 'GET_MATCHES_FAIL';

// --- MATCH ACTIONS (Submit / Confirm) ---
export const SUBMIT_MATCH_RESULT_REQUEST = 'SUBMIT_MATCH_RESULT_REQUEST';
export const SUBMIT_MATCH_RESULT_SUCCESS = 'SUBMIT_MATCH_RESULT_SUCCESS';
export const SUBMIT_MATCH_RESULT_FAIL = 'SUBMIT_MATCH_RESULT_FAIL';

export const CONFIRM_MATCH_RESULT_REQUEST = 'CONFIRM_MATCH_RESULT_REQUEST';
export const CONFIRM_MATCH_RESULT_SUCCESS = 'CONFIRM_MATCH_RESULT_SUCCESS';
export const CONFIRM_MATCH_RESULT_FAIL = 'CONFIRM_MATCH_RESULT_FAIL';

// --- SOCKET UPDATES ---
export const UPDATE_TOURNAMENT_SOCKET = 'UPDATE_TOURNAMENT_SOCKET';
export const UPDATE_MATCH_SOCKET = 'UPDATE_MATCH_SOCKET';

// --- CLEANUP ---
export const CLEAR_TOURNAMENT_ERRORS = 'CLEAR_TOURNAMENT_ERRORS';