// src/redux/actionTypes/userActionType.js
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CLEAR_REGISTRATION_STATUS = 'CLEAR_REGISTRATION_STATUS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CLEAR_LOGIN_SUCCESS_MESSAGE = 'CLEAR_LOGIN_SUCCESS_MESSAGE'; // <-- مضاف
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_USER_ERRORS = 'CLEAR_USER_ERRORS';
export const ADMIN_GET_MEDIATORS_REQUEST = "ADMIN_GET_MEDIATORS_REQUEST";
export const ADMIN_GET_MEDIATORS_SUCCESS = "ADMIN_GET_MEDIATORS_SUCCESS";
export const ADMIN_GET_MEDIATORS_FAIL = "ADMIN_GET_MEDIATORS_FAIL";

// طلب الانضمام كوسيط (المستخدم)
export const APPLY_MEDIATOR_REQUEST = "APPLY_MEDIATOR_REQUEST";
export const APPLY_MEDIATOR_SUCCESS = "APPLY_MEDIATOR_SUCCESS";
export const APPLY_MEDIATOR_FAIL = "APPLY_MEDIATOR_FAIL";
export const APPLY_MEDIATOR_RESET = "APPLY_MEDIATOR_RESET"; // لمسح الحالة

// جلب طلبات الانضمام المعلقة (الأدمن)
export const ADMIN_GET_MEDIATOR_APPS_REQUEST = "ADMIN_GET_MEDIATOR_APPS_REQUEST";
export const ADMIN_GET_MEDIATOR_APPS_SUCCESS = "ADMIN_GET_MEDIATOR_APPS_SUCCESS";
export const ADMIN_GET_MEDIATOR_APPS_FAIL = "ADMIN_GET_MEDIATOR_APPS_FAIL";

// معالجة طلب الانضمام (الأدمن)
export const ADMIN_PROCESS_MEDIATOR_APP_REQUEST = "ADMIN_PROCESS_MEDIATOR_APP_REQUEST";
export const ADMIN_PROCESS_MEDIATOR_APP_SUCCESS = "ADMIN_PROCESS_MEDIATOR_APP_SUCCESS";
export const ADMIN_PROCESS_MEDIATOR_APP_FAIL = "ADMIN_PROCESS_MEDIATOR_APP_FAIL";
export const ADMIN_PROCESS_MEDIATOR_APP_RESET = "ADMIN_PROCESS_MEDIATOR_APP_RESET"; // لمسح الحالة

// تحديث حالة الوسيط (الأدمن)
export const UPDATE_MEDIATOR_STATUS_REQUEST = "UPDATE_MEDIATOR_STATUS_REQUEST";
export const UPDATE_MEDIATOR_STATUS_SUCCESS = "UPDATE_MEDIATOR_STATUS_SUCCESS";
export const UPDATE_MEDIATOR_STATUS_FAIL = "UPDATE_MEDIATOR_STATUS_FAIL";

export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_BALANCE = "UPDATE_USER_BALANCE";