// src/redux/actionTypes/withdrawalActionTypes.js
export const CREATE_WITHDRAWAL_REQUEST = 'CREATE_WITHDRAWAL_REQUEST';
export const CREATE_WITHDRAWAL_SUCCESS = 'CREATE_WITHDRAWAL_SUCCESS';
export const CREATE_WITHDRAWAL_FAIL = 'CREATE_WITHDRAWAL_FAIL';
export const CREATE_WITHDRAWAL_RESET = 'CREATE_WITHDRAWAL_RESET';

// --- أنواع خاصة بالأدمن ---
export const ADMIN_GET_WITHDRAWALS_REQUEST = 'ADMIN_GET_WITHDRAWALS_REQUEST';
export const ADMIN_GET_WITHDRAWALS_SUCCESS = 'ADMIN_GET_WITHDRAWALS_SUCCESS';
export const ADMIN_GET_WITHDRAWALS_FAIL = 'ADMIN_GET_WITHDRAWALS_FAIL';

export const ADMIN_GET_WITHDRAWAL_DETAILS_REQUEST = 'ADMIN_GET_WITHDRAWAL_DETAILS_REQUEST';
export const ADMIN_GET_WITHDRAWAL_DETAILS_SUCCESS = 'ADMIN_GET_WITHDRAWAL_DETAILS_SUCCESS';
export const ADMIN_GET_WITHDRAWAL_DETAILS_FAIL = 'ADMIN_GET_WITHDRAWAL_DETAILS_FAIL';
export const ADMIN_CLEAR_WITHDRAWAL_DETAILS = 'ADMIN_CLEAR_WITHDRAWAL_DETAILS';

export const ADMIN_COMPLETE_WITHDRAWAL_REQUEST = 'ADMIN_COMPLETE_WITHDRAWAL_REQUEST';
export const ADMIN_COMPLETE_WITHDRAWAL_SUCCESS = 'ADMIN_COMPLETE_WITHDRAWAL_SUCCESS';
export const ADMIN_COMPLETE_WITHDRAWAL_FAIL = 'ADMIN_COMPLETE_WITHDRAWAL_FAIL';

export const ADMIN_REJECT_WITHDRAWAL_REQUEST = 'ADMIN_REJECT_WITHDRAWAL_REQUEST';
export const ADMIN_REJECT_WITHDRAWAL_SUCCESS = 'ADMIN_REJECT_WITHDRAWAL_SUCCESS';
export const ADMIN_REJECT_WITHDRAWAL_FAIL = 'ADMIN_REJECT_WITHDRAWAL_FAIL';
export const ADMIN_CLEAR_WITHDRAWAL_ERROR = 'ADMIN_CLEAR_WITHDRAWAL_ERROR';

export const GET_USER_WITHDRAWALS_REQUEST = 'GET_USER_WITHDRAWALS_REQUEST';
export const GET_USER_WITHDRAWALS_SUCCESS = 'GET_USER_WITHDRAWALS_SUCCESS';
export const GET_USER_WITHDRAWALS_FAIL = 'GET_USER_WITHDRAWALS_FAIL';

// export const GET_WITHDRAWAL_HISTORY_REQUEST = 'GET_WITHDRAWAL_HISTORY_REQUEST';
// export const GET_WITHDRAWAL_HISTORY_SUCCESS = 'GET_WITHDRAWAL_HISTORY_SUCCESS';
// export const GET_WITHDRAWAL_HISTORY_FAIL =    'GET_WITHDRAWAL_HISTORY_FAIL';

// export const ADMIN_APPROVE_WITHDRAWAL_REQUEST = 'ADMIN_APPROVE_WITHDRAWAL_REQUEST';
// export const ADMIN_APPROVE_WITHDRAWAL_SUCCESS = 'ADMIN_APPROVE_WITHDRAWAL_SUCCESS';
// export const ADMIN_APPROVE_WITHDRAWAL_FAIL = 'ADMIN_APPROVE_WITHDRAWAL_FAIL';
